Set minimum Rust version to 1.77.0
Inform Clippy of our minimum supported Rust version, so it won't advise us
to use #[expect] (which is too new).

We don't support older Rust because of cargo:: syntax in build.rs:

    error: the `cargo::` syntax for build script output instructions was added in Rust 1.77.0, but the minimum supported Rust version of `git-interactive-rebase-tool v2.4.1 (/home/bgilbert/sw/git-interactive-rebase-tool)` is 1.56.0.
    Switch to the old `cargo:rustc-check-cfg=cfg(allow_unknown_lints)` syntax (note the single colon).
    See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.